/* This file was generated by Supernova and should not be changed manually */
import 'package:flutter/material.dart';
import '../keys/font-sizes-keys.dart';

class AppFontSizes {
  static const Map<String, double> data = {
    AppFontSizes.fontSizeFontSizeManualFontSize1: 14,
  };
}