/* This file was generated by Supernova and should not be changed manually */
import 'package:flutter/material.dart';
import '../keys/spaces-keys.dart';

class AppSpaces {
  static const Map<String, double> data = {
    AppSpaces.spaceSpaceManuaSpace1: 3,
  };
}