/* This file was generated by Supernova and should not be changed manually */
import 'package:flutter/material.dart';
import '../keys/strings-keys.dart';

class AppStrings {
  static const Map<String, String> data = {
    /* Use when you want to set a width of 80 characters in Figma | Sentence made by AI. */
    AppStrings.string80Characters: "In space, no one can hear you scream due to the lack of air for sound to travel.",
  };
}