// Simple SVG to JSX converter that works in sandboxed environments
// No timers, no complex async operations

const attributeMap: Record<string, string> = {
  'accent-height': 'accentHeight',
  'accumulate': 'accumulate',
  'additive': 'additive',
  'alignment-baseline': 'alignmentBaseline',
  'alphabetic': 'alphabetic',
  'amplitude': 'amplitude',
  'arabic-form': 'arabicForm',
  'ascent': 'ascent',
  'attributename': 'attributeName',
  'attributetype': 'attributeType',
  'azimuth': 'azimuth',
  'basefrequency': 'baseFrequency',
  'baseline-shift': 'baselineShift',
  'baseprofile': 'baseProfile',
  'bbox': 'bbox',
  'begin': 'begin',
  'bias': 'bias',
  'by': 'by',
  'calcmode': 'calcMode',
  'cap-height': 'capHeight',
  'class': 'className',
  'clip': 'clip',
  'clip-path': 'clipPath',
  'clip-rule': 'clipRule',
  'clippathunits': 'clipPathUnits',
  'color': 'color',
  'color-interpolation': 'colorInterpolation',
  'color-interpolation-filters': 'colorInterpolationFilters',
  'color-profile': 'colorProfile',
  'color-rendering': 'colorRendering',
  'contentscripttype': 'contentScriptType',
  'contentstyletype': 'contentStyleType',
  'cursor': 'cursor',
  'cx': 'cx',
  'cy': 'cy',
  'd': 'd',
  'decelerate': 'decelerate',
  'descent': 'descent',
  'diffuseconstant': 'diffuseConstant',
  'direction': 'direction',
  'display': 'display',
  'divisor': 'divisor',
  'dominant-baseline': 'dominantBaseline',
  'dur': 'dur',
  'dx': 'dx',
  'dy': 'dy',
  'edgemode': 'edgeMode',
  'elevation': 'elevation',
  'enable-background': 'enableBackground',
  'end': 'end',
  'exponent': 'exponent',
  'externalresourcesrequired': 'externalResourcesRequired',
  'fill': 'fill',
  'fill-opacity': 'fillOpacity',
  'fill-rule': 'fillRule',
  'filter': 'filter',
  'filterres': 'filterRes',
  'filterunits': 'filterUnits',
  'flood-color': 'floodColor',
  'flood-opacity': 'floodOpacity',
  'font-family': 'fontFamily',
  'font-size': 'fontSize',
  'font-size-adjust': 'fontSizeAdjust',
  'font-stretch': 'fontStretch',
  'font-style': 'fontStyle',
  'font-variant': 'fontVariant',
  'font-weight': 'fontWeight',
  'for': 'htmlFor',
  'from': 'from',
  'fx': 'fx',
  'fy': 'fy',
  'g1': 'g1',
  'g2': 'g2',
  'glyph-name': 'glyphName',
  'glyph-orientation-horizontal': 'glyphOrientationHorizontal',
  'glyph-orientation-vertical': 'glyphOrientationVertical',
  'glyphref': 'glyphRef',
  'gradienttransform': 'gradientTransform',
  'gradientunits': 'gradientUnits',
  'hanging': 'hanging',
  'height': 'height',
  'horiz-adv-x': 'horizAdvX',
  'horiz-origin-x': 'horizOriginX',
  'ideographic': 'ideographic',
  'image-rendering': 'imageRendering',
  'in': 'in',
  'in2': 'in2',
  'intercept': 'intercept',
  'k': 'k',
  'k1': 'k1',
  'k2': 'k2',
  'k3': 'k3',
  'k4': 'k4',
  'kernelmatrix': 'kernelMatrix',
  'kernelunitlength': 'kernelUnitLength',
  'kerning': 'kerning',
  'keypoints': 'keyPoints',
  'keysplines': 'keySplines',
  'keytimes': 'keyTimes',
  'lengthadjust': 'lengthAdjust',
  'letter-spacing': 'letterSpacing',
  'lighting-color': 'lightingColor',
  'limitingconeangle': 'limitingConeAngle',
  'local': 'local',
  'marker-end': 'markerEnd',
  'marker-mid': 'markerMid',
  'marker-start': 'markerStart',
  'markerheight': 'markerHeight',
  'markerunits': 'markerUnits',
  'markerwidth': 'markerWidth',
  'mask': 'mask',
  'maskcontentunits': 'maskContentUnits',
  'maskunits': 'maskUnits',
  'mathematical': 'mathematical',
  'mode': 'mode',
  'numoctaves': 'numOctaves',
  'offset': 'offset',
  'opacity': 'opacity',
  'operator': 'operator',
  'order': 'order',
  'orient': 'orient',
  'orientation': 'orientation',
  'origin': 'origin',
  'overflow': 'overflow',
  'overline-position': 'overlinePosition',
  'overline-thickness': 'overlineThickness',
  'paint-order': 'paintOrder',
  'panose-1': 'panose1',
  'pathlength': 'pathLength',
  'patterncontentunits': 'patternContentUnits',
  'patterntransform': 'patternTransform',
  'patternunits': 'patternUnits',
  'pointer-events': 'pointerEvents',
  'points': 'points',
  'pointsatx': 'pointsAtX',
  'pointsaty': 'pointsAtY',
  'pointsatz': 'pointsAtZ',
  'preservealpha': 'preserveAlpha',
  'preserveaspectratio': 'preserveAspectRatio',
  'primitiveunits': 'primitiveUnits',
  'r': 'r',
  'radius': 'radius',
  'refx': 'refX',
  'refy': 'refY',
  'rendering-intent': 'renderingIntent',
  'repeatcount': 'repeatCount',
  'repeatdur': 'repeatDur',
  'requiredextensions': 'requiredExtensions',
  'requiredfeatures': 'requiredFeatures',
  'restart': 'restart',
  'result': 'result',
  'rotate': 'rotate',
  'rx': 'rx',
  'ry': 'ry',
  'scale': 'scale',
  'seed': 'seed',
  'shape-rendering': 'shapeRendering',
  'slope': 'slope',
  'spacing': 'spacing',
  'specularconstant': 'specularConstant',
  'specularexponent': 'specularExponent',
  'speed': 'speed',
  'spreadmethod': 'spreadMethod',
  'startoffset': 'startOffset',
  'stddeviation': 'stdDeviation',
  'stemh': 'stemh',
  'stemv': 'stemv',
  'stitchtiles': 'stitchTiles',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'strikethrough-position': 'strikethroughPosition',
  'strikethrough-thickness': 'strikethroughThickness',
  'string': 'string',
  'stroke': 'stroke',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-opacity': 'strokeOpacity',
  'stroke-width': 'strokeWidth',
  'surfacescale': 'surfaceScale',
  'systemlanguage': 'systemLanguage',
  'tablevalues': 'tableValues',
  'targetx': 'targetX',
  'targety': 'targetY',
  'text-anchor': 'textAnchor',
  'text-decoration': 'textDecoration',
  'text-rendering': 'textRendering',
  'textlength': 'textLength',
  'to': 'to',
  'transform': 'transform',
  'u1': 'u1',
  'u2': 'u2',
  'underline-position': 'underlinePosition',
  'underline-thickness': 'underlineThickness',
  'unicode': 'unicode',
  'unicode-bidi': 'unicodeBidi',
  'unicode-range': 'unicodeRange',
  'units-per-em': 'unitsPerEm',
  'v-alphabetic': 'vAlphabetic',
  'v-hanging': 'vHanging',
  'v-ideographic': 'vIdeographic',
  'v-mathematical': 'vMathematical',
  'values': 'values',
  'vector-effect': 'vectorEffect',
  'version': 'version',
  'vert-adv-y': 'vertAdvY',
  'vert-origin-x': 'vertOriginX',
  'vert-origin-y': 'vertOriginY',
  'viewbox': 'viewBox',
  'viewtarget': 'viewTarget',
  'visibility': 'visibility',
  'width': 'width',
  'widths': 'widths',
  'word-spacing': 'wordSpacing',
  'writing-mode': 'writingMode',
  'x': 'x',
  'x-height': 'xHeight',
  'x1': 'x1',
  'x2': 'x2',
  'xchannelselector': 'xChannelSelector',
  'xlink:actuate': 'xlinkActuate',
  'xlink:arcrole': 'xlinkArcrole',
  'xlink:href': 'xlinkHref',
  'xlink:role': 'xlinkRole',
  'xlink:show': 'xlinkShow',
  'xlink:title': 'xlinkTitle',
  'xlink:type': 'xlinkType',
  'xml:base': 'xmlBase',
  'xml:lang': 'xmlLang',
  'xml:space': 'xmlSpace',
  'xmlns': 'xmlns',
  'xmlns:xlink': 'xmlnsXlink',
  'y': 'y',
  'y1': 'y1',
  'y2': 'y2',
  'ychannelselector': 'yChannelSelector',
  'z': 'z',
  'zoomandpan': 'zoomAndPan'
}

export function simpleSvgToJsx(svg: string): string {
  let jsx = svg
  
  // Replace attributes
  Object.entries(attributeMap).forEach(([svgAttr, jsxAttr]) => {
    // Use a regex that matches the attribute in the context of an SVG tag
    const regex = new RegExp(`(\\s)${svgAttr}(=)`, 'gi')
    jsx = jsx.replace(regex, `$1${jsxAttr}$2`)
  })
  
  // Convert style attribute from string to object
  jsx = jsx.replace(/style="([^"]*)"/g, (match, styles) => {
    const styleObj: Record<string, string> = {}
    styles.split(';').forEach((style: string) => {
      const [key, value] = style.split(':').map((s: string) => s.trim())
      if (key && value) {
        // Convert kebab-case to camelCase
        const camelKey = key.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
        styleObj[camelKey] = value
      }
    })
    return `style={${JSON.stringify(styleObj)}}`
  })
  
  // Self-closing tags
  jsx = jsx.replace(/<([^>]+)\/>/g, '<$1 />')
  
  return jsx
}
