import { TokenType } from "@supernovaio/sdk-exporters"

export const DEFAULT_STYLE_FILE_NAMES: Record<TokenType, string> = {
  Color: "Color.kt",
  Typography: "Typography.kt",
  Dimension: "Dimension.kt",
  Size: "Size.kt",
  Space: "Space.kt",
  Opacity: "Opacity.kt",
  FontSize: "FontSize.kt",
  LineHeight: "LineHeight.kt",
  LetterSpacing: "LetterSpacing.kt",
  ParagraphSpacing: "ParagraphSpacing.kt",
  BorderWidth: "BorderWidth.kt",
  BorderRadius: "BorderRadius.kt",
  Duration: "Duration.kt",
  ZIndex: "ZIndex.kt",
  Shadow: "Shadow.kt",
  Border: "Border.kt",
  Gradient: "Gradient.kt",
  String: "String.kt",
  ProductCopy: "ProductCopy.kt",
  FontFamily: "FontFamily.kt",
  FontWeight: "FontWeight.kt",
  TextCase: "TextCase.kt",
  TextDecoration: "TextDecoration.kt",
  Visibility: "Visibility.kt",
  Blur: "Blur.kt"
}

export const DEFAULT_TOKEN_PREFIXES: Record<TokenType, string> = {
  Color: "color",
  Typography: "typography",
  Dimension: "dimension",
  Size: "size",
  Space: "space",
  Opacity: "opacity",
  FontSize: "fontSize",
  LineHeight: "lineHeight",
  LetterSpacing: "letterSpacing",
  ParagraphSpacing: "paragraphSpacing",
  BorderWidth: "borderWidth",
  BorderRadius: "borderRadius",
  Duration: "duration",
  ZIndex: "zIndex",
  Shadow: "shadow",
  Border: "border",
  Gradient: "gradient",
  String: "string",
  ProductCopy: "productCopy",
  FontFamily: "fontFamily",
  FontWeight: "fontWeight",
  TextCase: "textCase",
  TextDecoration: "textDecoration",
  Visibility: "visibility",
  Blur: "blur"
} 