import { TokenType } from "@supernovaio/sdk-exporters"

export const DEFAULT_TOKEN_TYPE_FILE_NAMES: Record<TokenType, string> = {
  Color: "ColorTokens.kt",
  Typography: "TypographyTokens.kt",
  Dimension: "DimensionTokens.kt",
  Size: "SizeTokens.kt",
  Space: "SpaceTokens.kt",
  Opacity: "OpacityTokens.kt",
  FontSize: "FontSizeTokens.kt",
  LineHeight: "LineHeightTokens.kt",
  LetterSpacing: "LetterSpacingTokens.kt",
  ParagraphSpacing: "ParagraphSpacingTokens.kt",
  BorderWidth: "BorderWidthTokens.kt",
  BorderRadius: "BorderRadiusTokens.kt",
  Duration: "DurationTokens.kt",
  ZIndex: "ZIndexTokens.kt",
  Shadow: "ShadowTokens.kt",
  Border: "BorderTokens.kt",
  Gradient: "GradientTokens.kt",
  String: "StringTokens.kt",
  ProductCopy: "ProductCopyTokens.kt",
  FontFamily: "FontFamilyTokens.kt",
  FontWeight: "FontWeightTokens.kt",
  TextCase: "TextCaseTokens.kt",
  TextDecoration: "TextDecorationTokens.kt",
  Visibility: "VisibilityTokens.kt",
  Blur: "BlurTokens.kt"
}

export const DEFAULT_TOKEN_PREFIXES: Record<TokenType, string> = {
  Color: "color",
  Typography: "typography",
  Dimension: "dimension",
  Size: "size",
  Space: "space",
  Opacity: "opacity",
  FontSize: "fontSize",
  LineHeight: "lineHeight",
  LetterSpacing: "letterSpacing",
  ParagraphSpacing: "paragraphSpacing",
  BorderWidth: "borderWidth",
  BorderRadius: "borderRadius",
  Duration: "duration",
  ZIndex: "zIndex",
  Shadow: "shadow",
  Border: "border",
  Gradient: "gradient",
  String: "string",
  ProductCopy: "productCopy",
  FontFamily: "fontFamily",
  FontWeight: "fontWeight",
  TextCase: "textCase",
  TextDecoration: "textDecoration",
  Visibility: "visibility",
  Blur: "blur"
} 