import { TokenType } from "@supernova-studio/pulsar-next"

export const AllTokenTypes: Array<TokenType> = [
  TokenType.color,
  TokenType.typography,
  TokenType.dimension,
  TokenType.size,
  TokenType.space,
  TokenType.opacity,
  TokenType.fontSize,
  TokenType.lineHeight,
  TokenType.letterSpacing,
  TokenType.paragraphSpacing,
  TokenType.borderWidth,
  TokenType.radius,
  TokenType.duration,
  TokenType.zIndex,
  TokenType.shadow,
  TokenType.border,
  TokenType.gradient,
  TokenType.string,
  TokenType.productCopy,
  TokenType.fontFamily,
  TokenType.fontWeight,
  TokenType.textCase,
  TokenType.textDecoration,
  TokenType.visibility,
  TokenType.blur,
]
